force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <label>Required Role</label>
    <referenceTo>RequiredRole__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>ProjectResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RequiredRole__c/RequiredRole__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Required Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RequiredRole__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Required Roles</relationshipLabel>
    <relationshipName>Required_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectSquadLeadAssignment.cls
public class ProjectSquadLeadAssignment {
    //------------------Método para ser llamado desde el Trigger "ProjectSquadLeadAssignment"-------------------//
    public static void onBeforeUpdate(List<Project__c>ProjectList,Map<Id,Project__c>ProjecMapOld){
        //Crearemos un subconjunto de Ids desde los Ids de "ProjectList" (Es decir, desde Trigger.New).
        set<Id>filteredProjectListIds = new set<Id>();
        for(Project__c project:ProjectList){
            if(project.Squad_Lead__c!=ProjecMapOld.get(project.Id).Squad_Lead__c){
                filteredProjectListIds.add(project.Id);
            }
        }
        //A continuación, listamos los "Project Resource" que están relacionados, como "nietos", a los proyectos que dispararon en un subconjunto de Trigger.New, aquellos cuyos Ids están en el set "filteredProjectListIds".
        List<Project_Resource__c>projectResourceList =[
            SELECT Id,Resource__c,Required_Role__r.Project__r.Id 
            FROM Project_Resource__c 
            WHERE Required_Role__r.Project__r.Id IN:filteredProjectListIds
        ];
        //A continuación crearemos una lista de Maps cuya "key" será el Id del proyecto que dispara el Trigger  cuyo "Value" serán todos los
        //registros de "Project Resource" relacionados, como "nietos" al proyecto.
        Map<Id,List<Project_Resource__c>>projectResourceMap =new Map<Id,List<Project_Resource__c>>();
        for(Project_Resource__c projectResource:projectResourceList){
            if(projectResourceMap.containsKey(projectResource.Required_Role__r.Project__r.Id)){
                projectResourceMap.get(projectResource.Required_Role__r.Project__r.Id).add(projectResource);
            }else{
                projectResourceMap.put(projectResource.Required_Role__r.Project__r.Id,new List<Project_Resource__c>{projectResource});
            }
        }
        //Iteraremos sobre cada Proyecto que disparo el Trigger para verificar que el "Squad Lead" que se le asigne es un "Recurso" que trabaja para dicho proyecto.
        for(Project__c project:ProjectList){
            List<Project_Resource__c>resourcesOfThisProject = projectResourceMap.get(project.Id);
            Integer numberOfResourcesInTheProject = resourcesOfThisProject.size();
            Integer counter = 0;
            for(Project_Resource__c resource:resourcesOfThisProject){
                if((project.Squad_Lead__c == resource.Resource__c)||(project.Squad_Lead__c==null)){
                    break;
                }else{
                    counter +=1;
                }
            }
            if(numberOfResourcesInTheProject == counter){
                project.addError('Please, assign a project resource from this project as the Squad Lead.');
            }
        }
    }
}